// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlgyiipllykuxrntbfnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsZ3lpaXBsbHlrdXhybnRiZm5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTY4NzEsImV4cCI6MjA2MDU3Mjg3MX0.sGjcsKA0TsdR18d3n0UWhwbdV6S-Jt3jxZQhDYKaxvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);